name: one_hand_progress_controller
description: Progress controller design for one handed usage
version: 0.0.1
homepage: https://github.com/deepseapenguin/one_hand_progress_controller

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter: